run:
  deadline: 180s
  tests: true
  skip-dirs:
  - .git
  - .tool
  - vendor
  - verify

linters-settings:
  dupl:
    threshold: 100
  gocyclo:
    min-complexity: 50

linters:
  enable:
  - govet
  - deadcode
  - golint
  - gocyclo
  disable-all: true

issues:
  exclude-rules:
  - linters:
    - golint
    text: ".*should not use dot dot imports"
